- name: ติดตั้งแอปบนเครื่อง Ubuntu
  hosts: ubuntu_servers
  become: true
  tasks:

    - name: อัปเดต apt cache
      apt:
        update_cache: yes

    - name: ติดตั้ง Nginx
      apt:
        name: nginx
        state: present

    - name: ติดตั้ง htop
      apt:
        name: htop
        state: present
